#ifndef DEFINE_INFO_H_INCLUDED
#define DEFINE_INFO_H_INCLUDED

#define PI 3.1415926535

#define TRANSPARANCE_INITIALE 255
#define ROUGE_I 255
#define BLEU_I 255
#define VERT_I 255

#define NBRE_CHARACTERES_MAX 256

#define V_ZOOM 1.02
#define XI_CAM 0.00
#define YI_CAM 0.00
#define ZOOM_INITIAL 1.00
#define VITESSE_CAMERA 600.00
#define SEUIL_ZOOM 3.500
#define LARGEUR_BORD_BOUGER_CAMERA 50.00

#define NBRE_ANIM_MAX 50

#define GRAVITE 1900.00

#define XI_OBJ XBASE/2.00
#define YI_OBJ YBASE/2.00

#define COULEUR_SCORE al_map_rgb(156,30,130)

//--MAP---
#define N_CASES_X 25    // opti : 25
#define N_CASES_Y 13    // opti : 13
#define TAILLE_BLOCX XBASED/double(N_CASES_X)
#define TAILLE_BLOCY YBASED/double(N_CASES_Y)
#define COEF_LAB1 25 // opti : 25
#define COEF_LAB2 6  // opti : 6

#define TOUCHE_RECOMMENCER ALLEGRO_KEY_ENTER

//---NBRE_IMAGES: NI_ --------
#define NI_LANCES_BOMBES 2
#define NI_BLOCS 1
#define NI_EXPLO1 25
#define NI_EXPLO2 17
#define NI_BOMBES 2
#define NI_EXPLO3 12
#define NI_EXPLO4 11



//---LANCES_BOMBES (LB)------
#define TAILLEC_LB_I 0.60
#define TAILLE_LBX XBASED/double(N_CASES_X)
#define TAILLE_LBY YBASED/double(N_CASES_Y)
#define VITESSE_LB_I 14000.000 //12000
#define NBRE_JOUEURS 2
#define PORTEE_BOMBE_I 1.20
#define TEMP_RECHARGE_BOMBE_JET_I 0.80

//--BOMBE---
#define VITESSE_ANIM_BOMBE 26.00
#define VITESSE_ANIM_BOMBE2 18.00
#define VITESSE_ANIM_BOMBE_CROIX 18.00 //18
#define VITESSE_ANIM_BOMBE_CROIX2 16.00
#define NBRE_BOMBES_MAX 8
#define TAILLE_BOMBESI 0.30
#define TAILLE_EXPLO1I 6.00
#define TAILLE_EXPLO2I 8.00
#define TAILLE_EXPLO3I 5.00
#define TAILLE_EXPLO4I 6.00
#define VITESSE_BOMBE_I 24000.00 //24000
#define DERNIER_ETAT_LETHAL_ANIM_EXPLO1 11
#define DERNIER_ETAT_LETHAL_ANIM_EXPLO2 10
#define DISTANCE_DEBUT_CENTRE_EXPLO_CROIX 50.00
#define COEFF_FIN_CENTRE_EXPLO_CROIX 0.75
#define TYPE_EXPLO_MUR 0
#define PORTEE_CROIX 4
#define DETRUIRE_MUR 0

#define FRIENDLY_FIRE 0

//------RESEAU------
#define NBRE_CHIFFRE_CODAGE_DOUBLE 8
#define NBRE_CHIFFRE_CODAGE_INT NBRE_CHIFFRE_CODAGE_DOUBLE
#define PLACEMENT_VIRGULE_CODAGE_DOUBLE 3 //millier Centaine Dizaine Unité Dixième Centième
#define N_CARACTERES_PACKET (N_CASES_X*N_CASES_Y+NBRE_BOMBES_MAX*8*5+2048)
#define TEMPS_ATTENTE_DEBUT_JEU 200 //ms
#endif // DEFINE_INFO_H_INCLUDED
